FROM node:18.17.0

WORKDIR /app/client

COPY client/package*.json ./

RUN npm install

COPY client/ ./

# Set environment variables
ENV NODE_ENV=development
ENV WDS_SOCKET_PORT=0

EXPOSE 3000

CMD ["npm", "start"]